set(FIRMWARE_SOURCES
  firmware/services/parameters/chassis_parameters.c
  firmware/platform/stm32/parameter_flash.c
  firmware/services/parameters/param_journal.c
  firmware/app/tasks/log_task.c
  firmware/os/log_queue.c
  firmware/platform/stm32/log_port.c
  firmware/os/failure_hooks.c
  firmware/app/failure.c
  firmware/platform/stm32/emergency_stop.c
  firmware/platform/stm32/board_io.c
  firmware/drivers/legacy/src/voltage_device.c
  firmware/platform/stm32/motor_hal.c
  Core/Src/adc.c
  Core/Src/can.c
  Core/Src/dma.c
  Core/Src/freertos.c
  Core/Src/gpio.c
  Core/Src/main.c
  Core/Src/spi.c
  Core/Src/stm32f4xx_hal_msp.c
  Core/Src/stm32f4xx_hal_timebase_tim.c
  Core/Src/stm32f4xx_it.c
  Core/Src/system_stm32f4xx.c
  Core/Src/tim.c
  Core/Src/usart.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c
  Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c
  Middlewares/Third_Party/FreeRTOS/Source/croutine.c
  Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
  Middlewares/Third_Party/FreeRTOS/Source/list.c
  Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
  Middlewares/Third_Party/FreeRTOS/Source/queue.c
  Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
  Middlewares/Third_Party/FreeRTOS/Source/tasks.c
  Middlewares/Third_Party/FreeRTOS/Source/timers.c
  firmware/algorithms/chassis/chassis_math.c
  firmware/algorithms/math/src/LevenbergMarquardt.c
  firmware/algorithms/math/src/adrc.c
  firmware/algorithms/math/src/cJSON.c
  firmware/algorithms/math/src/declination.c
  firmware/algorithms/math/src/filter.c
  firmware/algorithms/math/src/kalman3.c
  firmware/algorithms/math/src/kalmanVel.c
  firmware/algorithms/math/src/lowPassFilter.c
  firmware/algorithms/math/src/mathTool.c
  firmware/algorithms/math/src/matrix3.c
  firmware/algorithms/math/src/matrix6.c
  firmware/algorithms/math/src/pid.c
  firmware/algorithms/math/src/quaternion.c
  firmware/algorithms/math/src/rotation.c
  firmware/algorithms/math/src/simplepid.c
  firmware/algorithms/math/src/vector3.c
  firmware/app/startup.c
  firmware/app/tasks/chassis_task.c
  firmware/app/tasks/serial_task.c
  firmware/drivers/legacy/src/IIC.c
  firmware/drivers/legacy/src/lcd_init.c
  firmware/drivers/legacy/src/mpu6050.c
  firmware/drivers/legacy/src/oled_init.c
  firmware/drivers/motor/stm32_motor.c
  firmware/os/ports/freertos-10.3.1/GCC/ARM_CM4F/port.c
  firmware/platform/stm32/platform_time.c
  firmware/platform/stm32/serial_port.c
  firmware/platform/stm32/startup_stm32f407xx.S
  firmware/services/chassis_service.c
  firmware/services/legacy/src/key_proc.c
  firmware/services/legacy/src/lcd_proc.c
  firmware/services/legacy/src/mpu6050_proc.c
  firmware/services/legacy/src/oledfont.c
  firmware/services/legacy/src/rgb_proc.c
  firmware/services/protocol/star_dispatch.c
  firmware/services/protocol/star_protocol.c
  firmware/platform/syscalls.c
)
set(FIRMWARE_INCLUDES
  firmware/services/parameters
  firmware/drivers/motor
  Core/Inc
  Drivers/CMSIS/Device/ST/STM32F4xx/Include
  Drivers/CMSIS/Include
  Drivers/STM32F4xx_HAL_Driver/Inc
  Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
  Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS
  Middlewares/Third_Party/FreeRTOS/Source/include
  firmware/algorithms/chassis
  firmware/algorithms/math/inc
  firmware/app
  firmware/boards/stm32
  firmware/drivers/legacy/inc
  firmware/drivers/motor
  firmware/os
  firmware/os/ports/freertos-10.3.1/GCC/ARM_CM4F
  firmware/platform/stm32
  firmware/services
  firmware/services/legacy/inc
  firmware/services/protocol
)
