set(FIRMWARE_SOURCES
  os/key_events.c
  platform/tm4c/key_irq.c
  platform/tm4c/board_devices.c
  platform/tm4c/motor_io.c
  services/tm4c_legacy/src/buzzer_proc.c
  platform/tm4c/emergency_stop.c
  algorithms/tm4c_legacy/WP_Math.c
  Lib/src/driverlib/adc.c
  Lib/src/driverlib/aes.c
  Lib/src/driverlib/can.c
  Lib/src/driverlib/comp.c
  Lib/src/driverlib/cpu.c
  Lib/src/driverlib/crc.c
  Lib/src/driverlib/des.c
  Lib/src/driverlib/eeprom.c
  Lib/src/driverlib/emac.c
  Lib/src/driverlib/epi.c
  Lib/src/driverlib/flash.c
  Lib/src/driverlib/fpu.c
  Lib/src/driverlib/gpio.c
  Lib/src/driverlib/hibernate.c
  Lib/src/driverlib/i2c.c
  Lib/src/driverlib/interrupt.c
  Lib/src/driverlib/lcd.c
  Lib/src/driverlib/mpu.c
  Lib/src/driverlib/onewire.c
  Lib/src/driverlib/pwm.c
  Lib/src/driverlib/qei.c
  Lib/src/driverlib/shamd5.c
  Lib/src/driverlib/ssi.c
  Lib/src/driverlib/sw_crc.c
  Lib/src/driverlib/sysctl.c
  Lib/src/driverlib/sysexc.c
  Lib/src/driverlib/systick.c
  Lib/src/driverlib/timer.c
  Lib/src/driverlib/uart.c
  Lib/src/driverlib/udma.c
  Lib/src/driverlib/usb.c
  Lib/src/driverlib/watchdog.c
  algorithms/chassis/chassis_math.c
  algorithms/tm4c_legacy/WP_Math.c
  app/tm4c/FreeRTOS.c
  app/tm4c/control_task.c
  app/tm4c/main.c
  app/tm4c/pc_service.c
  drivers/tm4c/maoxiu_motor.c
  drivers/tm4c/src/lcd.c
  drivers/tm4c/src/lcd_init.c
  drivers/tm4c/src/mpu6050.c
  os/failure_hooks.c
  os/vendor/FreeRTOS-Kernel-10.5.1/event_groups.c
  os/vendor/FreeRTOS-Kernel-10.5.1/list.c
  os/vendor/FreeRTOS-Kernel-10.5.1/portable/GCC/ARM_CM4F/port.c
  os/vendor/FreeRTOS-Kernel-10.5.1/portable/MemMang/heap_4.c
  os/vendor/FreeRTOS-Kernel-10.5.1/queue.c
  os/vendor/FreeRTOS-Kernel-10.5.1/stream_buffer.c
  os/vendor/FreeRTOS-Kernel-10.5.1/tasks.c
  os/vendor/FreeRTOS-Kernel-10.5.1/timers.c
  platform/tm4c/bsp/src/bsp_adc.c
  platform/tm4c/bsp/src/bsp_gpio.c
  platform/tm4c/bsp/src/bsp_iic.c
  platform/tm4c/bsp/src/bsp_spi.c
  platform/tm4c/bsp/src/bsp_tim.c
  platform/tm4c/bsp/src/bsp_uart.c
  platform/tm4c/startup_tm4c123.S
  platform/tm4c/system.c
  services/chassis_service.c
  services/protocol/star_dispatch.c
  services/protocol/star_protocol.c
  services/tm4c_legacy/src/lcd_proc.c
  services/tm4c_legacy/src/mpu6050_proc.c
  services/tm4c_legacy/src/rgb_proc.c
  platform/syscalls.c
)
set(FIRMWARE_INCLUDES
  algorithms/tm4c_legacy
  .
  Lib
  Lib/inc
  Lib/src
  algorithms/chassis
  app/tm4c
  boards/tm4c
  drivers/tm4c
  drivers/tm4c/inc
  os
  os/vendor/FreeRTOS-Kernel-10.5.1/include
  os/vendor/FreeRTOS-Kernel-10.5.1/portable/GCC/ARM_CM4F
  platform/tm4c
  platform/tm4c/bsp/inc
  services
  services/protocol
  services/tm4c_legacy/inc
)
